# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'PureProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for PureProject
  
  pod 'QPToolSDk', :path => '/Users/qiupeng/QP/iOS/组件化/PrivatePod/QPToolSDk/QPToolSDk.podspec'
  
end
